### ISSUE TITLE
hyper client lifetime issue

### ISSUE THREAD

**Issue by jgraef** [jgraef/skunk#7]
I had to remove an unnecessary `'static` lifetime bound in hyper, so that we can mut-borrow connections to it. Currently the socks server needs this, because it wants to shut down the connections once the layer stack is done. But it is generally better not to require the connection to be static.

The workspace `Cargo.toml` contains a `patch` section to use my fix:

```toml
[patch.crates-io]
hyper = { git = "https://github.com/jgraef/hyper.git", branch = "non-static-client-io" }
```

Once the [PR](https://github.com/hyperium/hyper/pull/3667) is merged upstream (and released), we can remove that `patch`.
